### PR TITLE
Fix error caused by  writing bytes (instead of str) to error file

### PR DESCRIPTION
**Pull request by tdgroot**
I was receiving an error (in Python 3.8). Setting the file descriptor to `wb` instead of `w` fixed it. I also verify that the error output file contains useful information after writing. 

```
2020-04-29 13:52:03,854 nginx_config_reloader INFO     /home/timon/nginx
2020-04-29 13:52:03,907 nginx_config_reloader INFO     Config check failed
2020-04-29 13:52:03,907 nginx_config_reloader INFO     Listening for changes to /home/timon/nginx
^C[2020-04-29 13:53:36,585 pyinotify ERROR] add_watch: cannot watch /home/timon/nginx WD=-1, Errno=Bad file descriptor (EBADF)
[2020-04-29 13:53:36,585 pyinotify ERROR] add_watch: cannot watch /home/timon WD=-1, Errno=Bad file descriptor (EBADF)
2020-04-29 13:53:36,661 nginx_config_reloader INFO     Config check failed
2020-04-29 13:53:36,662 nginx_config_reloader INFO     Listening for changes to /home/timon/nginx
Traceback (most recent call last):
  File "/usr/local/bin/nginx_config_reloader", line 11, in <module>
    load_entry_point('nginx-config-reloader==20200319.154431', 'console_scripts', 'nginx_config_reloader')()
  File "/usr/local/lib/python3.8/site-packages/nginx_config_reloader/__init__.py", line 373, in main
    wait_loop(
  File "/usr/local/lib/python3.8/site-packages/nginx_config_reloader/__init__.py", line 333, in wait_loop
    notifier.loop()
  File "/usr/lib/python3.8/site-packages/pyinotify.py", line 1376, in loop
    self.process_events()
  File "/usr/lib/python3.8/site-packages/pyinotify.py", line 1276, in process_events
    self._sys_proc_fun.cleanup()  # remove olds MOVED_* events records
AttributeError: 'NoneType' object has no attribute 'cleanup'

```

### CODE REVIEW

**Comment by vdloo** [comment]
this breaks python2.7 compatibility:
```
root@abbsgf-testtest-magweb-cmbl /data/web/nginx # nginx_config_reloader --monitor  &
[1] 18244
root@abbsgf-testtest-magweb-cmbl /data/web/nginx # 2020-05-07 09:01:58,266 nginx_config_reloader INFO     /data/web/nginx
2020-05-07 09:01:58,319 nginx_config_reloader INFO     Config check failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nginx_config_reloader/__init__.py", line 220, in apply_new_config
    subprocess.check_output([NGINX, '-t'], stderr=subprocess.STDOUT)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/sbin/nginx', '-t']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/nginx_config_reloader", line 9, in <module>
    load_entry_point('nginx-config-reloader==20200507.105824', 'console_scripts', 'nginx_config_reloader')()
  File "/usr/lib/python3/dist-packages/nginx_config_reloader/__init__.py", line 378, in main
    recursive_watch=args.recursivewatch
  File "/usr/lib/python3/dist-packages/nginx_config_reloader/__init__.py", line 329, in wait_loop
    nginx_config_changed_handler.apply_new_config()
  File "/usr/lib/python3/dist-packages/nginx_config_reloader/__init__.py", line 225, in apply_new_config
    self.write_error_file(e.output.encode())
AttributeError: 'tests' object has no attribute 'encode'
```

**Comment by vdloo** [comment]
works fine on `python 3.7.3` which is what we'll have on the Debian Buster Hypernodes though:
```
root@uaijay-vdloo-magweb-cmbl /tmp # ps aux | grep nginx_config
root     17198  2.0  0.5  30340 21648 ?        Ss   09:05   0:00 /usr/bin/python3 /usr/bin/nginx_config_reloader --monitor
root     17260  0.0  0.0   6148   888 pts/0    S+   09:05   0:00 grep nginx_config
root@uaijay-vdloo-magweb-cmbl /tmp # /usr/bin/python3 --version
Python 3.7.3
root@uaijay-vdloo-magweb-cmbl /tmp # systemctl stop nginx-config-reloader
root@uaijay-vdloo-magweb-cmbl /tmp # /usr/bin/python3 /usr/bin/nginx_config_reloader --monitor &
[1] 17300
root@uaijay-vdloo-magweb-cmbl /tmp # 2020-05-07 09:06:25,209 nginx_config_reloader INFO     /data/web/nginx
2020-05-07 09:06:25,299 nginx_config_reloader INFO     Reloading nginx config
2020-05-07 09:06:25,299 nginx_config_reloader INFO     Listening for changes to /data/web/nginx

root@uaijay-vdloo-magweb-cmbl /tmp # echo "}}" >> /data/web/nginx/mag
magento2.flag  magmi.conf     
root@uaijay-vdloo-magweb-cmbl /tmp # echo "}}" >> /data/web/nginx/magmi.conf 
root@uaijay-vdloo-magweb-cmbl /tmp # 2020-05-07 09:06:36,437 nginx_config_reloader INFO     IN_CLOSE_WRITE detected on magmi.conf
2020-05-07 09:06:36,516 nginx_config_reloader INFO     Reloading nginx config
```

but for compatibility (and the Xenial Hypernodes) this still needs to work for py2 as well

**Comment by tdgroot** [comment]
Thanks for your review. I'll add the compatibility check for Python 2.7!

**Comment by tdgroot** [comment]
I went for a different approach: decode to string if necessary. 

Also added a `tox.ini` file to test for multiple python versions on my machine. I can remove it if you want, but I thought it was quite useful!

**Comment by vdloo** [comment]
very nice, thanks!
